### ISSUE TITLE
ENCUESTA

### ISSUE THREAD

**Issue by rbk0696** [rbk0696/DOCUMENTOS#1]
Complete la siguiente encuesta

(https://github.com/rbk0696/DOCUMENTOS/files/5043424/GIT.docx)
5043423/Heredia1.docx)

**Comment by beca06** [comment]
Ya estoy Completando la encuesta

**Comment by beca06** [comment]
Listo
[GIT.docx](https://github.com/rbk0696/DOCUMENTOS/files/5043459/GIT.docx)
